databases:
  - name: budget_app_production
    databaseName: budget_app_production_jbj8
    user: budget_app_production_jbj8_user

services:
  - type: web
    name: budgetApp
    runtime: ruby
    buildCommand: './bin/render-build.sh'
    startCommand: 'bundle exec puma -C config/puma.rb'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budget_app_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
